apiVersion: apps/v1
kind: Deployment
metadata:
  name: cka-nginx-5
spec:
  replicas: 5
  selector:
      matchLabels:
        app: cka-nginx-5
  template:
    metadata:
      labels:
        app: cka-nginx-5
    spec:
      containers:
        - image: nginx
          name: nginx
