apiVersion: apps/v1
kind: Deployment
metadata:
  name: cka-nginx-1
spec:
  selector:
    matchLabels:
      app: cka-nginx-1
  template:
    metadata:
      labels:
        app: cka-nginx-1
    spec:
      containers:
        - name: nginx
          image: nginx
