apiVersion: v1
kind: Pod
metadata:
  name: busybox-hello-world
spec:
  terminationGracePeriodSeconds: 5
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["while true; do echo hello world; date -u; sleep 30; done"]
  restartPolicy: Always
