apiVersion: v1
kind: Secret
metadata:
  name: secret-user-pass
type: Opaque
stringData:
  username: user
  password: pass
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-env
spec:
  terminationGracePeriodSeconds: 2
  containers:
    - name: busy
      image: busybox
      command: ["sleep", "3600"]
      env:
        - name: SECRET_USERNNAME
          valueFrom:
            secretKeyRef:
              name: secret-user-pass
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-user-pass
              key: password
